In [3]:
# pip install pandas sqlalchemy pymysql mysql-connector-python
# import mysql.connector
import pandas as pd;

In [4]:
df = pd.read_csv("data.csv",header=None)

In [5]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,117,118,119,120,121,122,123,124,125,126
0,NaN,2016,2016,2016,2015,2015,2015,2014,2014,2014,...,1978,1977,1977,1977,1976,1976,1976,1975,1975,1975
1,NaN,"Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...",...,"Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great..."
2,NaN,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,...,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years
3,Country,Both sexes,Male,Female,Both sexes,Male,Female,Both sexes,Male,Female,...,Female,Both sexes,Male,Female,Both sexes,Male,Female,Both sexes,Male,Female
4,Afghanistan,5.5 [3.4-8.1],3.2 [1.3-6.4],7.6 [4.3-12.4],5.2 [3.3-7.7],3.0 [1.3-6.0],7.3 [4.1-11.8],4.9 [3.1-7.3],2.8 [1.2-5.6],7.0 [4.0-11.3],...,0.9 [0.3-2.2],0.6 [0.2-1.2],0.2 [0.0-0.7],0.9 [0.3-2.1],0.5 [0.2-1.1],0.2 [0.0-0.7],0.8 [0.2-2.0],0.5 [0.2-1.1],0.2 [0.0-0.6],0.8 [0.2-2.0]

In [6]:
import pandas as pd

df = pd.read_csv("data.csv", header=None)

rows = []

# Loop through each country first
for r in range(4, len(df)):

    country = df.iloc[r, 0]

    # Then each year
    for col in range(1, df.shape[1], 3):

        year = int(df.iloc[0, col])

        # Then each sex
        for i in range(3):

            sex = df.iloc[3, col + i]

            obesity = str(df.iloc[r, col + i]).split(" ")[0]
            obesity = pd.to_numeric(obesity, errors="coerce")

            rows.append({
                "Country": country,
                "Year": year,
                "Sex": sex,
                "Obesity %": obesity
            })

final_df = pd.DataFrame(rows)

final_df.head(12)

        Country  Year         Sex  Obesity %
0   Afghanistan  2016  Both sexes        5.5
1   Afghanistan  2016        Male        3.2
2   Afghanistan  2016      Female        7.6
3   Afghanistan  2015  Both sexes        5.2
4   Afghanistan  2015        Male        3.0
5   Afghanistan  2015      Female        7.3
6   Afghanistan  2014  Both sexes        4.9
7   Afghanistan  2014        Male        2.8
8   Afghanistan  2014      Female        7.0
9   Afghanistan  2013  Both sexes        4.7
10  Afghanistan  2013        Male        2.7
11  Afghanistan  2013      Female        6.6

In [7]:
final_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 24570 entries, 0 to 24569
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    24570 non-null  str
 1   Year       24570 non-null  int64
 2   Sex        24570 non-null  str
 3   Obesity %  24066 non-null  float64
dtypes: float64(1), int64(1), str(2)
memory usage: 767.9 KB

In [8]:
final_df.describe()

               Year     Obesity %
count  24570.000000  24066.000000
mean    1995.500000     12.448932
std       12.121165     10.407428
min     1975.000000      0.100000
25%     1985.000000      3.900000
50%     1995.500000     10.600000
75%     2006.000000     18.175000
max     2016.000000     63.300000

In [9]:
final_df.shape

(24570, 4)

In [10]:
final_df.columns

Index(['Country', 'Year', 'Sex', 'Obesity %'], dtype='str')

In [11]:
final_df.head()

       Country  Year         Sex  Obesity %
0  Afghanistan  2016  Both sexes        5.5
1  Afghanistan  2016        Male        3.2
2  Afghanistan  2016      Female        7.6
3  Afghanistan  2015  Both sexes        5.2
4  Afghanistan  2015        Male        3.0

In [12]:
final_df.isnull().sum()

Country        0
Year           0
Sex            0
Obesity %    504
dtype: int64

In [13]:
final_df[final_df["Obesity %"].isnull()]

      Country  Year         Sex  Obesity %
14112  Monaco  2016  Both sexes        NaN
14113  Monaco  2016        Male        NaN
14114  Monaco  2016      Female        NaN
14115  Monaco  2015  Both sexes        NaN
14116  Monaco  2015        Male        NaN
...       ...   ...         ...        ...
20911   Sudan  1976        Male        NaN
20912   Sudan  1976      Female        NaN
20913   Sudan  1975  Both sexes        NaN
20914   Sudan  1975        Male        NaN
20915   Sudan  1975      Female        NaN

[504 rows x 4 columns]

In [14]:
final_df[final_df["Obesity %"].isna()]["Country"].unique()

<StringArray>
['Monaco', 'San Marino', 'South Sudan', 'Sudan']
Length: 4, dtype: str

In [15]:
final_df[final_df["Obesity %"].isna()].groupby("Country").size()

Country
Monaco         126
San Marino     126
South Sudan    126
Sudan          126
dtype: int64

In [16]:
final_df.to_csv("cleaned_data.csv", index=False)

In [18]:
import pandas as pd
from sqlalchemy import create_engine

USER = "root"
PASSWORD = "ayush123"
HOST = "localhost"
PORT = "3306"
DATABASE = "obesity_data"

connection_string = f"mysql+pymysql://{USER}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}"

engine = create_engine(connection_string)

table_name = "countrydata"

final_df.to_sql(table_name, con=engine, if_exists="replace", index=False)

print("Data successfully uploaded to MySql!")

Data successfully uploaded to MySql!